export type PasskeyErrorCode =
	| 'ERROR_PASSKEY_ABORTED'
	| 'ERROR_DISCOVERABLE_CREDENTIALS_UNSUPPORTED'
	| 'ERROR_USER_VERIFICATION_UNSUPPORTED'
	| 'ERROR_PASSKEY_EXISTS'
	| 'ERROR_GENERAL_ERROR_SEE_CAUSE_FIELD'
	| 'ERROR_ALGORITHMS_UNSUPPORTED'
	| 'ERROR_DOMAIN_MISMATCH'
	| 'ERROR_AUTHENTICATOR_UNKNOWN_ERROR'
