// Copyright (C) LoginID

export type PasskeyErrorCode =
  | "ERROR_PASSKEY_ABORTED"
  | "ERROR_DISCOVERABLE_CREDENTIALS_UNSUPPORTED"
  | "ERROR_USER_VERIFICATION_UNSUPPORTED"
  | "ERROR_PASSKEY_EXISTS"
  | "ERROR_GENERAL_ERROR"
  | "ERROR_ALGORITHMS_UNSUPPORTED"
  | "ERROR_DOMAIN_MISMATCH"
  | "ERROR_AUTHENTICATOR_UNKNOWN_ERROR";

export type StorageErrorCode =
  | "ERROR_STORAGE_NOT_FOUND"
  | "ERROR_STORAGE_FAILED"
  | "ERROR_STORAGE_FAILED_TO_OPEN"
  | "ERROR_STORAGE_UPDATE_FAILED";

export type ValidationErrorCode =
  | "ERROR_VALIDATION_EMPTY_INPUT"
  | "ERROR_VALIDATION_INVALID_FORMAT"
  | "ERROR_VALIDATION_REQUIRED_FIELD_MISSING"
  | "ERROR_VALIDATION_OUT_OF_RANGE"
  | "ERROR_VALIDATION_TYPE_MISMATCH";
