/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { Passkey } from './Passkey';
export type TxComplete = {
    authCred?: Passkey;
    /**
     * Internal passkey identifier
     */
    credentialId: string;
    /**
     * JWT access token
     */
    jwtAccess: string;
    /**
     * Random string generated by LoginID.
     */
    lNonce: string;
    /**
     * Random string.
     */
    nonce: string;
    /**
     * Computed hash value of the transaction.
     */
    txHash: string;
    /**
     * Internal transaction identifier
     */
    txId: string;
};

